---
apiVersion: v1
kind: Service
metadata:
  name: harbor-scanner-clair
spec:
  selector:
    app: harbor-scanner-clair
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-scanner-clair
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor-scanner-clair
  template:
    metadata:
      labels:
        app: harbor-scanner-clair
    spec:
      containers:
        - name: main
          image: goharbor/harbor-scanner-clair:poc
          imagePullPolicy: IfNotPresent
          env:
            - name: "SCANNER_LOG_LEVEL"
              value: "info"
            - name: "SCANNER_API_SERVER_ADDR"
              value: ":8080"
            - name: "SCANNER_API_SERVER_READ_TIMEOUT"
              value: "15s"
            - name: "SCANNER_API_SERVER_WRITE_TIMEOUT"
              value: "15s"
            - name: "SCANNER_CLAIR_URL"
              value: "http://harbor-harbor-clair:6060"
          ports:
            - name: api-server-port
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /probe/healthy
              port: api-server-port
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /probe/ready
              port: api-server-port
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
